"""add_new_features_v2

Revision ID: 8806f1a7c69c
Revises: 9907e6080985
Create Date: 2026-03-28 16:17:32.546425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8806f1a7c69c'
down_revision: Union[str, None] = '9907e6080985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('name', sa.String(), nullable=True))
    op.add_column('savings', sa.Column('category', sa.Enum('GENERAL', 'SCHOOL_FEES', 'RENT', 'EMERGENCY', 'CAR', 'HOUSE', 'LAND', 'PARTY', name='savingscategory'), nullable=True))
    op.add_column('transactions', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'full_name')
    op.drop_column('transactions', 'phone')
    op.drop_column('savings', 'category')
    op.drop_column('savings', 'name')
    # ### end Alembic commands ###
