"""initial_schema

Revision ID: 9907e6080985
Revises: 
Create Date: 2026-03-28 13:04:43.601346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9907e6080985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('savings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('savings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('savings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_id_number'), 'users', ['id_number'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id_number'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('savings', 'updated_at')
    op.drop_column('savings', 'created_at')
    op.drop_column('savings', 'is_active')
    op.drop_column('savings', 'end_date')
    # ### end Alembic commands ###
